font_family      Maple Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        16
disable_ligatures never

detect_urls yes

underline_hyperlinks always

copy_on_select no

paste_actions quote-urls-at-prompt,confirm

tab_bar_min_tabs            1
tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         slanted
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}

shell_integration enabled

macos_titlebar_color system

# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME
